import { Metadata } from 'next';

export const baseURL = new URL(
	process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000',
);

const seo = {
	metadataBase: baseURL,
	title: 'Create Next App',
	description: 'Generated by create next app',
} as Metadata;

export default seo;
